### ISSUE TITLE
Should 1MS timer really be set to micros?

### ISSUE THREAD

**Issue by eraxeg** [LeFish1/ESP8266_CoffeeRoaster#2]
See line 315

https://github.com/LeFish1/ESP8266_CoffeeRoaster/blob/2e5b4de39e0534b2694d45e3ebe0eaeea87e8222/src/main.cpp#L315

**Comment by LeFish1** [comment]
I always tend to set resolution of timers <10 ms to MICROS.

Since CPU power is not an issue on this project I would keep it that way.
